//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearningEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BlobDataStorage
    {
        public int BlobDataStorageSeq { get; set; }
        public string Name { get; set; }
        public string StorageName { get; set; }
        public string StorageData { get; set; }
        public int StatusCode { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByFunction { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByFunction { get; set; }
    }
}
